version: "3"
services:
  nginx_agency:
    image: nginx
    ports:
      - 80:80
    networks:
      - docker_net
    volumes:
      - $PWD/conf.d:/etc/nginx/conf.d
    container_name: nginx_agency


networks:
 docker_net:
  external: true
